# Generated by Django 5.2.3 on 2025-06-28 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_regular',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Nivel de advertencia - Genera alerta preventiva', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_maximo',
            field=models.PositiveIntegerField(default=0, help_text='Nivel máximo deseado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0, help_text='Nivel crítico - Genera alerta urgente'),
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_alerta', models.CharField(choices=[('MINIMO', 'Stock Mínimo Alcanzado'), ('REGULAR', 'Stock Regular Alcanzado'), ('MAXIMO', 'Stock Máximo Alcanzado')], max_length=10)),
                ('stock_actual', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('RESUELTA', 'Resuelta'), ('DESCARTADA', 'Descartada')], default='PENDIENTE', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('comentarios', models.TextField(blank=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_creadas', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.producto')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
