# Generated by Django 5.2.3 on 2025-06-28 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_stock_regular_alter_producto_stock_maximo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('RESERVA', 'Reserva'), ('CANCELACION', 'Cancelación de reserva')], max_length=15)),
                ('cantidad', models.PositiveIntegerField()),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='ubicacion_destino',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='ubicacion_origen',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['codigo'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='numero_serie',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_fisico',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock en almacén'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_reservado',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock reservado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='alertastock',
            index=models.Index(fields=['estado'], name='inventario__estado_c15222_idx'),
        ),
        migrations.AddIndex(
            model_name='alertastock',
            index=models.Index(fields=['producto', 'estado'], name='inventario__product_125d27_idx'),
        ),
        migrations.AddIndex(
            model_name='alertastock',
            index=models.Index(fields=['nivel_alerta', 'estado'], name='inventario__nivel_a_433068_idx'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='relacionado_con',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.movimiento'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MovimientoInventario',
        ),
    ]
