# Generated by Django 5.2.3 on 2025-06-18 00:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_kit_lote_proyecto_componentekit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('STOCK_BAJO', 'Stock Bajo'), ('VENCIMIENTO', 'Próximo a Vencer'), ('VENCIDO', 'Vencido'), ('SISTEMA', 'Sistema')], max_length=20)),
                ('nivel', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico')], max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.lote')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('PLANIFICADA', 'Planificada'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PLANIFICADA', max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Inventario',
                'verbose_name_plural': 'Auditorías de Inventario',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida'), ('TRANSFERENCIA', 'Transferencia'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolución')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('documento_referencia', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.proveedor')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.proyecto')),
                ('ubicacion_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='inventario.ubicacion')),
                ('ubicacion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='inventario.ubicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('CONFIRMADA', 'Confirmada'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
            },
        ),
        migrations.CreateModel(
            name='DetalleAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_sistema', models.PositiveIntegerField()),
                ('stock_fisico', models.PositiveIntegerField()),
                ('diferencia', models.IntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.auditoriainventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.ubicacion')),
            ],
            options={
                'unique_together': {('auditoria', 'producto', 'ubicacion')},
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.ordencompra')),
            ],
            options={
                'unique_together': {('orden_compra', 'producto')},
            },
        ),
    ]
