# Generated by Django 5.2.3 on 2025-06-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
